//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUHINH
    {
        public int ID { get; set; }
        public string HDH { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string OCUNG { get; set; }
        public string CARDDOHOA { get; set; }
        public string MANHINH { get; set; }
        public string PIN { get; set; }
        public string TRONGLUONG { get; set; }
        public string KETNOIMANG { get; set; }
        public string BANPHIM { get; set; }
        public string BAOHANH { get; set; }
        public Nullable<int> MASP { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
