//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanLaptop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DONHANGs = new HashSet<DONHANG>();
            this.FEEDBACKs = new HashSet<FEEDBACK>();
            this.GIOHANGs = new HashSet<GIOHANG>();
        }
        [Key]
        [Required]
        public int MAKH { get; set; }
        [Required(ErrorMessage = "Họ tên không được để trống")]
        [DisplayName("Họ và tên")]
        public string HOTEN { get; set; }
        [Required(ErrorMessage = "Ngày sinh không được để trống")]
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        public string DIACHI { get; set; }
        [Required(ErrorMessage = "Điện thoại không được để trống")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Email không được để trống")]
        public string GMAIL { get; set; }
        public Nullable<System.DateTime> NGAYDK { get; set; }
        [MinLength(5, ErrorMessage = "Tên đăng nhập phải ít nhất 5 kí tự.")]
        [Required(ErrorMessage = "Tên đăng nhập không được để trống")]
        public string USERNAME { get; set; }
        [Required(ErrorMessage = "Mật Khẩu không được để trống")]
        [StringLength(15, MinimumLength = 6, ErrorMessage = "Mật Khẩu phải từ 6  đến 15 kí tự.")]
        public string PASS { get; set; }
        public Nullable<int> MAQL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEEDBACK> FEEDBACKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        public virtual QUANLY QUANLY { get; set; }
    }
}
