//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTIMAGE
    {
        public int MAHA { get; set; }
        public string HA { get; set; }
        public Nullable<int> MASP { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
